# NumPy Introduction
Small introduction to NumPy, including basic commands, conventions, etc. <br>
Very similar to traditional MATLAB commands

In [2]:
import numpy as np

### Creating arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,3,4,5,6,7,8])
a[2]

3

`arange` similar to Python `range` command

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [16]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([[1,2,3],
          [3,4,5],
          [7,8,9]
          ])
n

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

To access elements of 2D NumPy array:

In [24]:
n[:,2]

array([3, 5, 9])

### Randomly generated arrays

In [28]:
np.random.rand(5,2) # Pseudo random

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [30]:
np.random.randn(6,1)    # Sampled from normal distribution

array([[-0.0191305 ],
       [ 1.17500122],
       [-0.74787095],
       [ 0.00902525],
       [-0.87810789],
       [-0.15643417]])

In [32]:
np.random.randint(low=0, high=99, size=(4,4))

array([[52, 76, 50,  4],
       [90, 63, 79, 49],
       [39, 46,  8, 50],
       [15,  8, 17, 22]])

### Element-wise operations

In [34]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [40]:
b = (10 * a) ** 2
b

array([   0,  100,  400,  900, 1600])

In [41]:
a + b

array([   0,  101,  402,  903, 1604])

In [45]:
a * b

array([   0,  100,  800, 2700, 6400])

### Comparison Operations

In [4]:
a = np.array([0,1,5,5,4])
a

array([0, 1, 5, 5, 4])

In [52]:
a >= 2

array([False, False,  True,  True,  True])

In [5]:
b = np.random.randint(low = 0, high = 10, size = (5))
b

array([0, 5, 1, 7, 1])

In [67]:
a > b

array([False, False,  True,  True, False])

In [6]:
a[a > b]

array([5, 4])

In [71]:
b[a < b]

array([9, 5])

### Summarising Operations

In [76]:
a = np.random.rand(5)
a

array([0.98315345, 0.44135492, 0.50400044, 0.32354132, 0.25974475])

In [77]:
a.mean()

0.5023589748746096

In [80]:
b = np.random.rand(5,5)
b

array([[0.18662715, 0.11058315, 0.27405925, 0.01025004, 0.62935972],
       [0.29517231, 0.18728654, 0.09528805, 0.28375581, 0.21492438],
       [0.28560373, 0.47140986, 0.54949682, 0.84511312, 0.9885097 ],
       [0.04886809, 0.23211825, 0.64331143, 0.16146656, 0.87014589],
       [0.21740243, 0.74175504, 0.65302051, 0.79888551, 0.03124756]])

In [96]:
for i in range(5):
    print(b[i,:].min())

0.010250039399590904
0.09528805226080372
0.2856037339109023
0.04886808622935135
0.031247562265261597
