# **Linear Algebra Refresher**

In [2]:
import numpy as np

### **Vector operations**

In [3]:
u = np.array([2,4,6,8])
u

array([2, 4, 6, 8])

In [5]:
v = np.array([1, 3, 7, 0])
v

array([1, 3, 7, 0])

In [6]:
u + v

array([ 3,  7, 13,  8])

### **Multiplication**

In [7]:
# Dot product
# u * v = u'v

def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0] # Vectors same size

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [8]:
vector_vector_multiplication(u, v)

56.0

In [9]:
# NumPy equivalent
u.dot(v)

56

In [45]:
U = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
U[:,2]

array([3, 6, 9])

In [15]:
np.shape(U)

(3, 3)

In [22]:
n = np.shape(U)[1]
n

3

In [33]:
v = np.array([2,4,6])

In [38]:
# Matrix-vector multiplication
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result


In [39]:
matrix_vector_multiplication(U, v)

array([ 28.,  64., 100.])

In [41]:
# NumPy equivalent
U.dot(v)

array([ 28,  64, 100])

In [65]:
# Matrix-matrix multiplication
def matrix_matrix_multiplication(U, V):
    assert U.shape[0] == V.shape[1]
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]

    result = np.zeros((num_rows, num_rows))

    for i in range(num_rows):
        result[:,i] = matrix_vector_multiplication(U, V[:,i])

    return result

In [69]:
U = np.array([[1,2,3,4],
              [4,5,6,7],
              [7,8,9,10]])
U.shape

(3, 4)

In [68]:
V = np.array([[7,8,9],
              [4,5,6],
              [1,2,3],
              [1,1,1]])
V.shape

(4, 3)

In [70]:
matrix_matrix_multiplication(U, V)

array([[ 22.,  28.,  34.],
       [ 61.,  76.,  91.],
       [100., 124., 148.]])

In [72]:
U.dot(V)

array([[ 22,  28,  34],
       [ 61,  76,  91],
       [100, 124, 148]])

### **Identity matrix**

In [74]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### **Matrix inversion**

In [102]:
# Only square matrices have inverses
# Determinant =! 0
M = np.array([[10,2,3],
              [4,5,6],
              [1,20,3]])

In [103]:
np.linalg.det(M)

-837.0000000000008

In [104]:
M_inv = np.linalg.inv(M)
M_inv.dot(M)

array([[ 1.00000000e+00,  5.89805982e-17, -3.55618313e-17],
       [ 0.00000000e+00,  1.00000000e+00, -4.16333634e-17],
       [ 2.08166817e-17, -2.77555756e-17,  1.00000000e+00]])