# Introduction to Machine Learning

<hr>

In [1]:
import pandas as pd
import numpy as np

### NumPy - Array Operations

In [13]:
np.zeros(5), \
    np.ones(5), \
        np.arange(5), \
            np.full(5, 5), \
                np.linspace(0, 5, 6)

(array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]),
 array([0, 1, 2, 3, 4]),
 array([5, 5, 5, 5, 5]),
 array([0., 1., 2., 3., 4., 5.]))

In [31]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### NumPy - Random Operations

In [36]:
np.random.rand(5,5)

array([[0.04481934, 0.18277153, 0.13701141, 0.39441625, 0.43565423],
       [0.152967  , 0.75917902, 0.87190414, 0.46268082, 0.62559474],
       [0.6811259 , 0.25374564, 0.94725652, 0.55115418, 0.89203043],
       [0.09015251, 0.07053187, 0.56862989, 0.50402608, 0.51592182],
       [0.14369818, 0.23239503, 0.84161   , 0.63681019, 0.2848687 ]])

In [37]:
np.random.randint(0, 10, (5,5))

array([[3, 5, 8, 2, 6],
       [6, 6, 7, 4, 9],
       [0, 6, 3, 0, 9],
       [0, 2, 8, 0, 4],
       [0, 2, 8, 7, 7]])

### NumPy - Linear Algebra

In [42]:
np.linalg.det(np.random.rand(5,5)), \
    np.linalg.inv(np.random.rand(5,5))

(-0.032982706105094364,
 array([[ 1.13121664,  2.50488981, -1.81517144,  0.43756694, -2.09808558],
        [-4.61689894, -0.20799984,  6.26470838, -1.08061789, -2.71481631],
        [ 3.37722076,  0.22254011, -5.26880252,  2.39871012,  2.41192504],
        [ 1.50312784, -0.43773854, -1.72623734, -2.34951688,  4.58941463],
        [-1.78291732, -1.64954081,  3.9367967 ,  0.9080806 , -2.52230695]]))